// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlYOTPA_Tju2HrzQIdjDGy52QHPAxpneg',
    appId: '1:584684159693:android:fa04aca3561c41b9761f84',
    messagingSenderId: '584684159693',
    projectId: 'phd-peer',
    storageBucket: 'phd-peer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGhoZnjQmnLCf-Tn5xhZFd_QUlqqkA9M',
    appId: '1:584684159693:ios:1a619e5bd5031139761f84',
    messagingSenderId: '584684159693',
    projectId: 'phd-peer',
    storageBucket: 'phd-peer.appspot.com',
    androidClientId: '584684159693-a8034qvgb16l9khchsjvklnhen3kn8dv.apps.googleusercontent.com',
    iosClientId: '584684159693-r19ilfrni43jje2gtso9u7aubpjdkt5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.phdPeer',
  );
}
